name: inception
pack: packtest
description: Update myself when I am updated.
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: github
criteria:
  trigger.body.ref:
    type: 'eq'
    pattern: 'refs/heads/master'
  trigger.body.repository.full_name:
    type: 'eq'
    pattern: 'partkyle-test/packtest'
action:
  ref: packs.install
  parameters:
    register: all
    packs:
      - packtest
    repo_url: '{{trigger.body.repository.full_name}}'
notify:
  on-complete:
    message: "\"@channel: Action succeeded.\""
    routes:
      - "hipchat"
