name: run_unit_tests_on_comment
pack: packtest
description: Update status to pending on PR
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: github
criteria:
  trigger.body.comment.body:
    type: matchregex
    pattern: "(re)?test\\s+this\\s+please"
action:
  ref: packtest.run_unit_tests
  parameters:
    repo: '{{trigger.body.repository.name}}'
    sha: '{{trigger.body.comment.commit_id}}'
    user: '{{trigger.body.repository.owner.login}}'
