name: run_unit_tests_on_pull_request
pack: packtest
description: Update status to pending on PR
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: github
action:
  ref: packtest.run_unit_tests
  parameters:
    repo: '{{trigger.body.repository.name}}'
    sha: '{{trigger.body.pull_request.head.sha}}'
    user: '{{trigger.body.repository.owner.login}}'
